import { AppProvider } from "@/context/AppContext";
import "./globals.css";
import { SocketProvider } from "@/context/SocketContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <SocketProvider>
            {children}
          </SocketProvider>
        </AppProvider>
      </body>
    </html>
  );
}
